### PR TITLE
This commit changes the responsibility of managing floating ips on

### PR DESCRIPTION
**Pull request by jtopjian**
an instance from Neutron to Nova via the os-floating-ips api.

### CODE REVIEW

**Comment by jtopjian** [comment]
I'm opening this PR to move discussion from the Terraform PR to here.

Some quick notes about this PR:
1. I plan to add some acceptance tests whenever the variable issue has been resolved.
2. I have tested this on two different clouds: nova-network and Neutron-based. On the Neutron-based cloud, I even tested instances with multiple networks attached and the os-floating-ips API was able to automatically determine what network the floating IP should be attached to -- so no need to specify a port ID.

Discussion at hand:

I understand what @ggiamarchi is saying. Unfortunately I have not been able to find a definitive resource that states that floating IPs on instances should be managed by Neutron for Neutron clouds. I understand that it's definitely possible to do, but at the same time, if it can all be done through the Nova API, maybe it should stay within Nova?

Even from using the `nova` command-line tool, all network and floating IP actions are accessed through the Nova API. For example:

``` shell
$ nova --debug floating-ip-list
```

This same argument can be made for the other Nova API extensions such as volumes and security groups. In fact, this provider is currently doing all security group work through the Nova API when a Neutron API exists:

http://developer.openstack.org/api-ref-networking-v2.html#security_groups

I fully understand the importance of Neutron Floating IPs for other Neutron resources, but in this case, my opinion is that whatever can be contained within Nova should stay within Nova.

If consensus is to use both Neutron and Nova for instance Floating IPs, I'll close this PR and complement the current instance resource with the os-floating-ips extension rather than remove the Neutron stuff.

**Comment by jtopjian** [comment]
cc @julienvey

**Comment by ggiamarchi** [comment]
I think your point 3 in https://github.com/jrperritt/terraform/pull/11 is a good thing and also the solution to the problem.

Floating ip management should be handled only in `openstack_compute_floatingip_v2` and `openstack_networking_floatingip_v2`. Rather than replace neutron by nova here it is probably better (and more portable) to completely remove the `floating_ip` attribute.

That way, the whole floating ip management will be done by dedicated resources only. What do you think about that ?

**Comment by jtopjian** [comment]
I think that's definitely a possible solution. I have one concern about it, which is why I described it as "unintuitive":

What if the user must use the floating IP in order to access the instance for the provisioning step? Is Terraform able to defer the provisioning in this case? Or would the provisioning resources have to be added to the floating ip resource?

**Comment by ggiamarchi** [comment]
Actually this behaviour can be seen as unintuitive regarding to the nova API. However this match the neutron API conception.

By the way, your point about instance provisioning is an important thing. I can take time tomorrow to make tests about that if you haven't already planned to do it.

**Comment by jtopjian** [comment]
Go for it :smile: 

If I get some time, I'll try some testing as well, but I don't know if I'll be able to get to it.

**Comment by jtopjian** [comment]
I made PRs #13 and #14 to show alternative ways of accomplishing this. As the commit message says, they're quick sketches :)

**Comment by jrperritt** [comment]
Was there a consensus on this? #14 seems like a reasonable way to handle it to me.

**Comment by jtopjian** [comment]
#14 sounds like a good option to me.

**Comment by jrperritt** [comment]
:+1:

**Pull request closed without merging**
