### PR TITLE
Instance volume attach

### PR DESCRIPTION
**Pull request by jtopjian**
This commit adds the ability for instances to attach volumes from within their resource.

### CODE REVIEW

**Comment by jtopjian** [comment]
Similar to the `getImageID` function in my other pull request, the `attach` and `detach` functions here can be used by other resources.

What's the best way for dealing with this? In the plugin I was working on, I began putting these functions in a file called `helpers.go`, but maybe that's not the best practice?

**Comment by jrperritt** [comment]
Which other resources can use the `attach` and `detach` functions?

**Comment by jtopjian** [comment]
Volumes :)

While it might be counter-intuitive to attach volumes to instances via a volume resource, it might have some uses. 

But more importantly, detatching a volume via the volume resource upon deletion ensures a clean delete. A volume must be in "available" state before it can be deleted. Most of the time this will be done by the instance (if a proper relation exists) but it's a good fall-back.

**Comment by jrperritt** [comment]
Is there an Cinder operation to attach/detach to an instance? I missing it in the docs.

Also, I'm trying to understand the use case: If you have a volume attached to an instance, and you want to delete the instance, then you detach the volume via the `volume` resource operation before deleting the instance? Or do you have a volume attached to an instance and you want to delete the volume, so you detach the volume via the `volume` resource operation before deleting the volume?

**Comment by jtopjian** [comment]
I don't believe there's a Cinder operation. I think everything is handled via the volumeattach extension, which I find a little strange.

Here's what I've observed from everyday use. I have not actually dug into the API code to see where these actions are happening. As well, stepping through these may make me change my mind about whether a volume needs to do any of this.
1. If a user deletes an instance that has an attached volume, the volume will automatically be detached prior to the instance's deletion. The user does not have to intervene at all. The end result is a deleted instance and a volume in "available" state. The user can then proceed to cleanly delete the volume. This holds true when deleting an instance/volume combo with this PR.
2. If a user attempts to delete a volume that is attached to an instance, the user will receive an error message that the volume is currently attached to an instance and must be in an "available" state prior to deletion. So the user must either issue a "detach" or delete the instance.

Both of these actions make sense because the instance would be the source of the volume's activity. If the instance does not exist, it's safe to say that the volume can be automatically detached. The logic works in reverse: you should not delete a volume while it's owner still exists as reads/writes may still be happening. Instead, you should explicitly "detach" first, so the OS knows of the disconnect.

But at the same time, I suppose the `nova volume-delete` or `cinder delete` commands could simply perform a detach prior to deletion... I guess they're just siding on caution.

In Terraform:
1. If a relationship exists between an instance and volume, upon a `destroy` action, the instance will be deleted first (thus automatically detaching), and then the volume will be deleted next.
2. If a relationship does not exist, for whatever reason, the volume may be attempted to be deleted first, which will cause an error and probably a weird state.
3. If a previous Terraform action caused the state to become weird, the relationship between the instance and volume could be broke and repeated attempts to `destroy` might always make the volume be deleted first (and thus a perpetual error).

I've played around with recreating these scenarios, and they're not terribly difficult to recreate. What I'm wondering is if I'm putting too much thought into potential edge cases or cases where the user blatantly did something they shouldn't have.

So when I talk about placing a "detach" action as part of the volume's Delete phase in terraform, my intention is to help the volume get to an "available" state so the Delete happens cleanly. I haven't seen a way where Terraform will simply pass over an action if it's not ready to happen yet. There's the "wait for state" stuff, but that just blocks until a resource is in the matched state.

Thoughts?

**Comment by jrperritt** [comment]
Ok, very well-explained. That is clear to me (I think).
Currently, there is a `detachVolumesFromInstance` function for the compute instance resource. It sounds like there should be a different `detachInstancesFromVolume` function for the block storage volume resource that is called as part of the 'delete' operation. In Gophercloud, A `volume` has a field named `Attachments` which should contain all the compute instance IDs to which the volume is attached. Does that sound reasonable or is there still more to do there?

**Comment by jtopjian** [comment]
Yes, the "tl;dr" of all of this would have been "just use a similarly named function in the volume resource" :smiley: 

However, I suppose it was worth covering the use-cases and potential issues of volume attachments in Terraform.

And one other thought I had, though only for illustrative purposes, is that to avoid any conflicts between a volume resource, instance resource, and their attached relationship, an atomic `openstack_compute_with_volume` resource could exist that bundles an instance and volume. That way creation, modifications, and deletions are all self-contained.

**Comment by jrperritt** [comment]
Yeah, I think we should leave these functions as they are, create new ones for the volume resource, and hold off on the `openstack_compute_with_volume` resource for now.

**Comment by jtopjian** [comment]
re `openstack_compute_with_volume`: absolutely -- I didn't intend to create one. It was just used as an example to illustrate the relation between the two :)

I'll rebase this tonight and work on the volume detach portion in another PR.

**Comment by jrperritt** [comment]
:+1:

**Comment by jtopjian** [comment]
Rebased and added documentation.

**Comment by jrperritt** [comment]
Thank you :)

**Pull request merged**
