### PR TITLE
Adds network_service parameter to openstack_compute_instance_v2 resource

### PR DESCRIPTION
**Pull request by jtopjian**
This commit is a quick sketch of using a parameter to explicitly set
the network service to use for an instance's network-related actions.

### CODE REVIEW

**Comment by jtopjian** [comment]
Does this look OK? Or is there room for improvement?

**Comment by lnguyen** [comment]
hi @jtopjian I'm having inconsistent results, as in it worked then stopped working, using the neutron way to attach floating ip. Using the compute api to attach floating IP I've consistently been able to attach floating ip to my compute instance. Is it better to default to that? I'm no openstack expert just wanted to see your opinion

**Comment by jtopjian** [comment]
@longnguyen11288 That's interesting. Off the top of my head, I don't know what would cause the issue. Can you provide the output of:

``` shell
TF_LOG=1 terraform apply
```

for when it's not working?

Can you also provide your `.tf` file (with any sensitive information removed) as well as the steps you did to produce the failure? This way, I can try to reproduce the issue on a Neutron cloud and see if I (or someone else here) can find the cause.

**Comment by lnguyen** [comment]
So there is no errors it proceed like it happen. I even printed out neutron result and it seem like it worked and got 200. My tf is very simple https://gist.github.com/longnguyen11288/4550a887956994ec44a1 I'm not sure if its my openstack having issues but I was able to reproduce it on 2 different openstack

**Comment by lnguyen** [comment]
When I used compute api to assign floating ip it works everytime.

**Comment by jtopjian** [comment]
OK - thank you for the info. I will try to reproduce this when I get a chance. 

One more question: Are you having Neutron problems without this patch? Or are you still seeing this problem with this patch and `network_service` set to `neutron`?

**Comment by lnguyen** [comment]
Without this patch, also I changed it to use compute api vs neutron api before I saw this PR.

**Comment by lnguyen** [comment]
Question, did the terraform have to include the external net in networks? I noticed code looks for first network to get id

**Comment by jtopjian** [comment]
I did some quick tests and this is not working for me, either. You're right: the code is getting the first network ID regardless of if the instance is even using that network or if that network can even support a floating IP.

Fortunately this is easily reproducible in my environment since the first network I created does not support floating IPs. :smile: 

Unfortunately, from doing a cursory search, there is no easy way to tie an instance ID to a port ID that supports a floating IP.

What probably needs to happen is:
1. The network ID (external net ID) of the given floating IP needs to be looked up and stored.
2. Loop through all networks given in the `network` block and query for each subnet belonging to that network. Store the subnet IDs. It's safe to assume IPv4 only. IPv6 floating IPs don't exist and I don't think there's any intention on supporting them soon.
3. Query for all routers that the tenant owns.
4. Find a router that has an external_gateway_info field that matches the external net ID of the floating IP (found in step 1).
5. For each router, query for the ports of the router.
6. For each port, find a match between the subnet ID of the router and the subnet ID(s) found in step 2. It's safe to say that by this point, there should only be one match, unless the user has chosen to use multiple interfaces on the same network. But let's keep it simple for now.
7. Get the Port ID of the matched subnet ID for the instance.
8. _Now_ you can associate a floating IP ID with a Port ID and be fairly confident that it will work.

IMO, that's a mess. A short-cut would be to add an attribute to the `network` block of instances of something like `floating_ip_pool`. The value would be the pool that allows attachment of floating IPs from that pool. 

Now, what would happen:
1. The Floating IP would be looked up and an external net ID would be found.
2. For each network specified, find one that has `floating_ip_pool` set.
3. For each result (multiple floating IP pools can exist), look up the external net ID of each pool.
4. When a match is made, look up the Port ID of the instance on that network and associate the IP.

That's still significantly more complex than just using `os-floating-ips`. I really hate to beat a dead horse on this, so I'm going to post to the openstack mailing list and ask for advise on what to do in this situation. Hopefully a definitive answer can be found this way.

**Comment by lnguyen** [comment]
Thanks for update. Hopefully someone can have a good answer. It seem like horizon itself uses os-floating-ips.

**Comment by jtopjian** [comment]
I think it uses Neutron. This is why you're presented with a list of ports when you want to associate a floating IP. If you choose the wrong port, Horizon will return an error.

I think that's an acceptable workflow for an interactive web-session, but I don't think it's really acceptable for Terraform. If you choose the wrong port, you have to either try to recover a failed run or resume a failed run with modified information.

Regarding my idea of `floating_ip_pool` in the network block, perhaps a better option is to move the `floating_ip` attribute to the `network` block. That might cut down on the number of steps.

**Comment by jtopjian** [comment]
@jrperritt I haven't gotten a response on the openstack mailing list. Do you have any contacts you can check with?

Otherwise, to support both APIs, here's what I'm thinking:
- move `floating_ip` to the `network` block
- Move the association and disassociation logic similarly
- For updates, check and see if `floating_ip` was the only changed attribute, and if so, don't do anything drastic like rebuild the instance.
- If there is a Floating IP set for a specific network, use that network for the AccessV\* stuff.
- Allow networks to be specified by common names rather than UUIDs (nice to have).

The benefits of all this is that it will assume that the user has placed the `floating_ip` attribute in the correct network block (meaning: the network that can support the given floating IP), and therefore remove all of the complexity described in the above comments.

What do you think?

**Comment by jrperritt** [comment]
@jtopjian I can ask some people about it tomorrow, but I think you're on the right track with your last comment (associating the floating IP with the network).

**Comment by jtopjian** [comment]
#18 should fix the problems reported by @longnguyen11288. It also supersedes this PR, so I'll close it.

**Pull request closed without merging**
