### PR TITLE
user_data support

### PR DESCRIPTION
**Pull request by cbuben**
Mostly stolen from: https://github.com/jtopjian/terraform-provider-openstack/blob/master/openstack/resource_openstack_instance.go

### CODE REVIEW

**Comment by Bersekyr** [comment]
Hello,
I've tried to test it. I got "'openstack_compute_instance_v2.test' error: : invalid or unknown key: user_data"
I might have done something bad, but it seems that there is a problem somewhere. It would be great if you could have a look, this would be a killer feature for me.
Have a great day ;-)

**Comment by jtopjian** [comment]
@Bersekyr Both the acceptance test and a demo `tf` file worked for me. If you're getting "unknown key", it sounds like the provider wasn't compiled or moved into place?

@cbuben Do you think you could rebase this against the lastest cleanup patch?

**Comment by cbuben** [comment]
@jtopjian rebased on top of e2e7abf

**Comment by jrperritt** [comment]
Is this ready to merge?

**Comment by jtopjian** [comment]
@cbuben Thanks!

@jrperritt I've done some basic tests and it works. Other than a doc update (which could be a separate patch), I think this is good to go.

**Comment by jrperritt** [comment]
:+1:

**Comment by cbuben** [comment]
@jrperritt (Gig 'em, Aggies; I'm '97)
@jtopjian
@Bersekyr 

Thanks, everyone!

**Comment by jrperritt** [comment]
@cbuben :+1: WH07P

**Pull request merged**
