### PR TITLE
Compute network refactor

### PR DESCRIPTION
**Pull request by jtopjian**

### CODE REVIEW

**Comment by jtopjian** [comment]
This is a big one with a lot of changes. No doubt there's some work to be done.

I'll also update the docs when this is closer to being finalized.

**Comment by jtopjian** [comment]
@jrperritt looks like some of this can be simplified once gophercloud #378 is merged.

**Comment by jtopjian** [comment]
If #378 is used instead, then the mac addresses will have to go away. I'm 60/40 on being OK with that.

**Comment by jtopjian** [comment]
Actually, maybe just scratch all of that. 

The results of ListAddresses doesn't return floating IPs, whereas the server.Addresses information does. This allows an easy way of determining if a server has the floating IP attached in the same areas as collecting the IP addresses. Otherwise a separate area will need created to handle reading the floating IP from the server.

With all of that said, though, I'd think there was a cleaner way of collecting all network information than the mess that I created. :smile:

**Comment by jtopjian** [comment]
This latest commit cleans up the mess I made with parsing addresses and merging it with network information. It also adds the tenantnetworks extension so nova-network users only have to specify either a network uuid or name -- not both.

tenantnetworks can also be used to obtain the network uuid/name mapping for Neutron networks, but it might be best to leave the two separate?

**Comment by haklop** [comment]
I tried your PR on my Neutron based provider with this configuration:

```
resource "openstack_compute_instance_v2" "http_server" {
    name = "http_server"
    image_id = "43241fdb-22d5-4b44-ac1b-dba1e9923767"
    flavor_name = "1_vCPU_RAM_512M_HD_10G"
    key_pair = "tf"
    network_service = "neutron"

    network = {
        name = "network_1"
        floating_ip = "${openstack_compute_floatingip_v2.foo.address}"
    }
}

resource "openstack_compute_floatingip_v2" "foo" {
    pool = "PublicNetwork-01"
}
```

The first apply works well, I've got an instance with a floating IP associate to it. But if I apply it twice, there is an error:

```
{"NeutronError": {"message": "Cannot associate floating IP 89.30.84.34 (34c18f52-cdbb-4a37-936b-fbbd7417b4e4) with port 4bccbc2f-fbef-41ff-837c-1a580845164f using fixed IP 192.168.199.17, as that fixed IP already has a floating IP on external network fb0c4a19-d4f1-4129-ab3f-41dc9ef1d7fa.", "type": "FloatingIPPortAlreadyAssociated", "detail": ""}}
```

The resourceComputeInstanceV2Read method doesn't retrieve the floating IPs so Terraform try to associate again the floating IP. I think that on resourceInstanceNetworks you should retrieve all the floatings IPs associate to the fixed_ip_v4 instead of using rawMap["floating_ip"] by using the floatings IPs API: `GET /v2.0/floatingips?fixed_ip_address=1.2.3.4`.

**Comment by jtopjian** [comment]
Thanks for the notes :)

I'll look into this as soon as I can -- I'm out of the office at the moment. 

When I was testing this the other week, I noticed that if I did an `apply` then `show`, the floating IP wasn't visible. If I did a `refresh` then `show`, the floating IP showed up. The issue you're reporting sounds related.

I thought it might have been caused by a delay between Neutron and Nova: the floating IP request was sent, but it was not confirmed in time for when Terraform finished. Do you think that's possible? Or is it simply that `resourceInstanceNetworks` needs fixed up?

I'm unable to look into this at the moment, so I'm more thinking out loud :smile:

**Comment by jtopjian** [comment]
@haklop I've looked into this a little but I'm unable to reproduce the issue. I have a few questions:
- Are you able to reproduce this issue on each double-apply or is this only happening sometimes?
- Is `89.30.84.34` the floating IP that was created upon the first `apply` or was a second floating IP somehow created (maybe Terraform didn't acknowledge that a floating IP was created during the first run)?
- Is `192.168.199.17` somehow pre-mapped with a floating IP?

I'm also looking into your suggestion about polling floating IPs via the fixed IP -- I think that's a good idea.

**Comment by haklop** [comment]
- Yes I'm able to reproduce this issue on each double-apply.
- `89.30.84.34` is the floating IP that was created upon the first apply. resourceComputeInstanceV2Read doesn't retrieve floatings IPs so Terraform believes that the floating IP was disassociate and try to associate it.
- `192.168.199.17` is allocated by the `network_1` dhcp and is not pre-mapped with a floating IP.

**Comment by jtopjian** [comment]
@haklop Thanks for the info. I apologize for the barrage of questions -- since I can't reproduce this issue, I'm kind of running blind.

While `resourceComputeInstanceV2Read` doesn't explicitly retrieve floating IPs from the corresponding network service's floating IP API, it retrieves them from the `server.Addresses` dataset. This dataset contains all network information related to the instance including fixed and floating IPs, so it _shouldn't_ be necessary to do an explicit call to the floating IP API.

But, I made some changes that check to see if a fixed IP has a floating IP attached to it by explicitly looking it up in the Neutron Floating IP API. Right now it only accounts for the first floating IP found. You can find the changes here:

https://github.com/jtopjian/terraform/tree/compute-network-refactor2

I made a separate branch for now as I'm still not 100% sure I understand the cause of the problem and  so it might take a few attempts. 

Please let me know if this helps. If not, let me know if you can see where these changes can be made better.

**Comment by hartzell** [comment]
I built the compute-network-refactor branch.

When I use this config file:

```
  name = "tf-test"
  image_id = "62896feb-0c93-49bd-93a3-23f597d3f9ec"
  flavor_id = "n1.small"
  key_pair = "alanturing-nebula-keypair"

  network_service = "nova-network"
  network {
    name = "my-net"
    floating_ip = "${openstack_compute_floatingip_v2.test.address}"
  }
}

resource "openstack_compute_floatingip_v2" "test" {
    pool = "nebula"
}
```

I get this response:

```
allons:20150212-terraform-openstack-sandbox georgewh$ terraform apply
openstack_compute_floatingip_v2.test: Creating...
  address:     "" => "<computed>"
  fixed_ip:    "" => "<computed>"
  instance_id: "" => "<computed>"
  pool:        "" => "nebula"
  region:      "" => "RegionOne"
openstack_compute_floatingip_v2.test: Creation complete
openstack_compute_instance_v2.test: Creating...
  access_ip_v4:          "" => "<computed>"
  access_ip_v6:          "" => "<computed>"
  flavor_id:             "" => "n1.small"
  flavor_name:           "" => "<computed>"
  image_id:              "" => "62896feb-0c93-49bd-93a3-23f597d3f9ec"
  image_name:            "" => "<computed>"
  key_pair:              "" => "alanturing-nebula-keypair"
  name:                  "" => "tf-test"
  network.#:             "" => "1"
  network.0.fixed_ip_v4: "" => "<computed>"
  network.0.fixed_ip_v6: "" => "<computed>"
  network.0.floating_ip: "" => "10.29.92.49"
  network.0.mac:         "" => "<computed>"
  network.0.name:        "" => "my-net"
  network.0.port:        "" => "<computed>"
  network.0.uuid:        "" => "<computed>"
  network_service:       "" => "nova-network"
  region:                "" => "RegionOne"
openstack_compute_instance_v2.test: Error: Expected HTTP response code [200 204] when accessing [GET http://proxy.nebula.gene.com:8774/v2/6ba254b787054e23a3abe5030f416b4f/os-tenant-networks], but got 404 instead
404 Not Found

The resource could not be found.


Error applying plan:

1 error(s) occurred:

* Expected HTTP response code [200 204] when accessing [GET http://proxy.nebula.gene.com:8774/v2/6ba254b787054e23a3abe5030f416b4f/os-tenant-networks], but got 404 instead
404 Not Found

The resource could not be found.



Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I'm not sure what's up with .../os-tenant-networks, but here's the result of a bit of poking around using the "nova" command line tool:

```
vagrant@openstacker:~$ nova network-list
+----+-------+------+
| ID | Label | Cidr |
+----+-------+------+
+----+-------+------+
vagrant@openstacker:~$ nova net-list
ERROR: Not found (HTTP 404)
vagrant@openstacker:~$
```

**Comment by jtopjian** [comment]
@hartzell Thank you for trying it out :smile: 

It looks like Nebula isn't supporting a way to view network info. Pinging @devcamcar to see if he has a suggestion. 

BTW: you'll definitely want to change `my-net` to something else unless your nova-network is really called `my-net`. But since `nova net-list`  or `nova network-list` isn't reporting anything, it's not going to work regardless of what value you use.

**Comment by devcamcar** [comment]
@jtopjian @hartzell In our 1.2 and earlier releases, the `nova network-list` command will return an empty list because there is only one default flat DHCP network.  If no network UUID is explicitly requested, then Terraform should not be making an effort to determine it.  Simply don't pass this parameter to Nova and it will handle this correctly with the defaults.

For our 1.3 and later releases, the `nova network-list` command will return the VLAN networks available for the tenant.

**Comment by jtopjian** [comment]
@devcamcar Thank you for the input. I definitely agree about not requiring a network UUID and letting Nova do the work and this is still the case with these changes. The issue is that I've tried to move `floating_ip` into the network block to cut down on the large amount of work needed to attach a floating IP using the Neutron API.

I'll try to figure out a way around this or go back to the drawing board.

**Comment by jtopjian** [comment]
@jrperritt I'm thinking of resurrecting #12 with some enhancements. #12 uses the `os-floating-ips` api extension to manage floating IPs for instances. After reading through the Nova code, it looks as though it sufficiently handles Neutron as well:
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/contrib/floating_ips.py#L166
- https://github.com/openstack/nova/blob/master/nova/network/neutronv2/api.py#L1076

You can see in that the nova.network.neutronv2.api file, port IDs lookups and such are handled by Nova. Any attempt at this in Terraform, IMO, is just duplication.

The only area I can think of where it could become difficult is determining what fixed IP to associate the floating IP with. As mentioned before, my tests showed that Nova successfully applied the floating IP to the right fixed IP even when I had the instance on multiple Neutron networks, though maybe that was just [luck](https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/contrib/floating_ips.py#L202-L206). To ensure against this, maybe `floating_ip` can be changed from a parameter to a block:

```
resource "openstack_compute_instance_v2" "test" {
...
  floating_ip {
    floating_ip = "${openstack_compute_floatingip_v2.test.address}"
    fixed_ip = "10.0.0.10"
  }
}
```

I think `os-floating-ips` deserves a chance. After trying to figure out alternative ways of supporting both the Nova and Neutron API, it's still looking like the best solution.

Short of this, the only other sane solution I can think of right now is moving all associate / disassociate functionality to the respective `openstack_compute_floatingip` and `openstack_network_floatingip` resources so Nova and Neutron are completely separated. But I still think that solution feels odd, as described in #12.

Thoughts?

**Comment by hartzell** [comment]
@devcamcar  Is the 404 that the code in this branch gets when trying to GET this URL

```
http://proxy.nebula.gene.com:8774/v2/6ba254b787054e23a3abe5030f416b4f/os-tenant-networks
```

the same as the 404 that this `nova` command returns?

```
vagrant@openstacker:~$ nova net-list
ERROR: Not found (HTTP 404)
vagrant@openstacker:~$
```

Would you expect `net-list` to work?  It appears that we're running 1.2 (that's the version number in the URL to the documentation).

**Comment by jrperritt** [comment]
@jtopjian As long as it works with Neutron, that's fine with me.

**Comment by jtopjian** [comment]
Thanks everyone for the input. I'm closing this in favor of #23 which I think will resolve the reported issues. @hartzell and @haklop please give it a shot and let me know if you have any problems.

**Pull request closed without merging**
