### PR TITLE
dns zone v2 updates

### PR DESCRIPTION
**Pull request by jtopjian**

### CODE REVIEW

**Comment by jtopjian** [comment]
Let me know if you have any questions. The `ValueSpecs` stuff is a bit awkward and I've been meaning to see if it can be cleaned up.

Docs are coming up a bit later today.

Feel free to squash these commits with disregard to ownership. The entire commit set should have two commits: vendor, everything else.

**Comment by jrperritt** [comment]
> The ValueSpecs stuff is a bit awkward and I've been meaning to see if it can be cleaned up.

Yeah, I didn't know what that was for, but I saw it in all the other resources, so I added it.

> Feel free to squash these commits with disregard to ownership. The entire commit set should have two commits: vendor, everything else.

To clarify, are you saying you'd be OK with there only being 2 commits or that the Terraform project insists on there only being 2 commits? I'd prefer that you keep credit for your work.

**Comment by jtopjian** [comment]
> Yeah, I didn't know what that was for, but I saw it in all the other resources, so I added it.

They're used to inject arbitrary key/value pairs into the request body. A contributor has been adding them as needed for their cloud. As long as they don't break anything, I've been OK with it, but I should review it soon.

> To clarify, are you saying you'd be OK with there only being 2 commits or that the Terraform project insists on there only being 2 commits? I'd prefer that you keep credit for your work.

It's totally fine either way with me. I've just force pushed a commit with docs. If you squash your non-vendor commits into 1, then the 3 total commits is quite clean.

**Comment by jtopjian** [comment]
Oh, missed this:  There's no requirement at all for 2 commits. The only strict requirement is the separate vendor one. But the number of commits as they are right now might make someone flag a messy git history :)

**Comment by jrperritt** [comment]
> If you squash your non-vendor commits into 1, then the 3 total commits is quite clean.

OK, that's what I'll do then.

And I've made a bad decision: I should've merged this and then rebased. I'll resolve the conflicts.

**Comment by jtopjian** [comment]
> And I've made a bad decision: I should've merged this and then rebased. I'll resolve the conflicts.

If it gets too hairy, we can always start over.

**Comment by jrperritt** [comment]
@jtopjian OK, I'm too tired to be productive so I'm not gonna worry about it. Can you squash all these down into 1 or 2 commits?

**Comment by jtopjian** [comment]
Yep. I'll get that done now. Probably the best thing to do is for me to just open a new PR at Terraform with the clean commits.

Since I have commits in the PR, I'll get a Terraform core to do a quick code review. Best case scenario is it gets merged tomorrow. Should make it into the next version in any case.

**Comment by jrperritt** [comment]
Thank you for your help and patience

**Comment by jtopjian** [comment]
no worries at all. :)

**Pull request closed without merging**
