### PR TITLE
Compute network refactor

### PR DESCRIPTION
**Pull request by jtopjian**

### CODE REVIEW

**Comment by jtopjian** [comment]
A limitation at the moment is that only 1 neutron network can be used with a floating IP. You can specify several neutron network, but only one can be related to a floating IP. And that network _must_ be specified first. I'd be grateful for ideas on how to get around this or maybe this is an acceptable limitation.

To use with nova network:

```
resource "openstack_compute_floatingip_v2" "test" {
  pool = "nova"
}

resource "openstack_compute_instance_v2" "test" {
  name = "tf-test"
  image_name = "Ubuntu 14.04"
  flavor_name = "m1.tiny"
  floating_ip = "${openstack_compute_floatingip_v2.test.address}"
  security_groups = ["default"]
}
```

To use with neutron:

```
resource "openstack_networking_floatingip_v2" "testfp" {
  pool = "floating_ips"
}

resource "openstack_compute_instance_v2" "test" {
  name = "tf-test"
  image_name = "CirrOS"
  flavor_name = "m1.tiny"
  security_groups = ["default"]
  floating_ip = "${openstack_networking_floatingip_v2.testfp.address}"

  network {
    name = "mgmt"
    fixed_ip_v4 = "192.168.100.25"
  }

  network {
    name = "hnl"
  }

  network {
    uuid = "3a789018-6b9f-4816-8ae2-6240f46839b6"
  }
}
```

Notes on the above:
- You do not have to specify a network at all for nova-network. The default network will be automatically used. Floating IP attachment will work fine, too.
- You can specify multiple neutron networks either by name or UUID.
- You can specify fixed addresses via the `fixed_ip_v*` parameters.
- Network parameters will be automatically computed/filled in. This includes IPv4, IPv6, name, UUID, and MAC address.
- In the Neutron example, the `mgmt` network is the network that supports floating IPs. It must be the first specified network.

**Comment by jtopjian** [comment]
Rebased

**Comment by jrperritt** [comment]
If no one else chimes in, I can try to find a solution to the Neutron issue on Monday.

**Comment by hartzell** [comment]
This seems to work, but crashes at the end of `terraform apply`.

[Here's a gist of the crash](https://gist.github.com/hartzell/a86168a6fb865902f428).

Here's how I built it (the patch step just fixes the colored warnings that have evolved in the cli library):

```
  871  mkdir go
  872  git clone -b compute-network-refactor3 https://github.com/jtopjian/terraform $GOPATH/src/github.com/hashicorp/terraform
  873  cd $GOPATH/src/github.com/hashicorp/terraform
  874  ls
  875  make updatedeps
  877  find . -type d | grep azure
  878  rm -rf ./builtin/bins/provider-azure ./builtin/providers/azure
  879  make updatedeps
  880  make dev
  882  find . -type d | grep digitalocean
  883  find . -type d | grep digitalocean | xargs rm -rf
  884  patch -p1  < ~/tmp/diffs
  885  make dev
  886  find . -type d | grep cloudstack
  887  find . -type d | grep cloudstack | grep buil | xargs rm -rf
  888  make dev
```

g.

**Comment by jtopjian** [comment]
@hartzell: Thanks for the report. Can you try the latest?

**Comment by hartzell** [comment]
Did a `git fetch` and a `make dev`.  Binaries appear to have been rebuilt (via `ls -l`).

Crashed again.  [Gist here](https://gist.github.com/hartzell/04de523023365f46ea8e).

g.

**Comment by jtopjian** [comment]
Hm. The crash log shows it failed on the same line again (`/resource_openstack_compute_instance_v2.go:803`), but with the latest commit, line 803 is not trying to do a string conversion.

Can you compare line 803 with what's on github vs your local copy? Maybe the changes weren't pulled in?

**Comment by jtopjian** [comment]
@jrperritt My idea to resolve the "first neutron network" is to add a flag to the `networks` block that identifies the network as a floating IP enabled network. 

In order to allow that, os-floating-ips needs updated in gophercloud. I discovered an [extension](https://github.com/openstack/nova/commit/1b2c121f133b15d0fe3f6ebdb131ac9998bc4b83) to the os-floating-ips extension that allows a fixed ip to be specified. I have a patch ready to go, but want to first confirm that everything is working for George with this current PR before making further changes.

**Comment by hartzell** [comment]
My mistake, too much svn & not enough git in my daily diet.  Forgot the `git merge` after the `git fetch`....

Worked fine.

Thanks!

**Comment by jtopjian** [comment]
woohoo! Thank you for verifying!

OK, I'm going to start making the changes to handle multi-neutron networks. 

@hartzell If it's OK with you, I'll need another test tomorrow or Friday to make sure nothing on your side broke.

**Comment by hartzell** [comment]
@jtopjian, fine with me.  I'll try to keep on top of it (work permitting).

**Comment by jtopjian** [comment]
I just pushed 3 commits. The first two should resolve the "first neutron network" issue. As per the commit notes, if a neutron network is tagged with `set_floating_ip`, that network will be used to associate the floating IP. I'm happy to change the name of the flag if `set_floating_ip` is not suitable.

One caveat is that these commits rely on [this](https://github.com/rackspace/gophercloud/pull/403) patch to gophercloud. If anyone wants to test this, they will need to apply that patch or wait until it gets merged.

The third commit fixed a typo for cases where no network was specified (usually nova-network environments). After fixing this typo, doing a `terraform show` should now print the obtainable network information.

At this point, I think this branch is ready for others to test and to give feedback.

**Comment by hartzell** [comment]
I just noticed that it's still possible to shoot yourself in the foot if you use a floating IP address that's in use by another instance.

Here's an example:

```
resource "openstack_compute_floatingip_v2" "test" {
  pool = "nebula"
}

resource "openstack_compute_instance_v2" "test" {
  name = "tf-test"
  image_id = "62896feb-0c93-49bd-93a3-23f597d3f9ec"
  flavor_id = "n1.small"
  key_pair = "alanturing-nebula-keypair"
  floating_ip = "${openstack_compute_floatingip_v2.test.address}"
  security_groups = ["default"]
}

resource "openstack_compute_instance_v2" "test-the-other" {
  name = "tf-test-2"
  image_id = "62896feb-0c93-49bd-93a3-23f597d3f9ec"
  flavor_id = "n1.small"
  key_pair = "alanturing-nebula-keypair"
  floating_ip = "${openstack_compute_floatingip_v2.test.address}"
  security_groups = ["default"]
}
```

I'd like to see this generate an error.  Instead, one instance ends up with the floating ip, the other looses, but everything appears to have worked.

I believe that Openstack allows this type of foot shooting.  Is it possible to at least have terraform keep track of what _it_ is doing and not let shoot myself in the foot?  I could still step on something allocated via other tools, but it seems better than nothing.

**Comment by jtopjian** [comment]
@hartzell That's a really interesting scenario and I think it deserves some thought and more discussion. I think that can wait until we get the fundamentals sorted out, though, since there might be other areas where preventative foot-shooting would be nice.

If you're able to launch instances and attach floating IPs, I think that's a huge win at this point. :smile:

**Comment by julienvey** [comment]
@hartzell Yes, it's a common scenario unfortunately, to stole a floating_ip. But I'm not really sure it is terraform responsibilty to manage that. 

This "Bug" or "Feature" would find its use-case with Terraform. For instance you could always use the same floating IP to provision mutliple servers sequentially

```
resource "openstack_compute_floatingip_v2" "test" {
  pool = "nebula"
}

resource "openstack_compute_instance_v2" "test" {
  name = "tf-test"
  image_id = "62896feb-0c93-49bd-93a3-23f597d3f9ec"
  flavor_id = "n1.small"
  key_pair = "alanturing-nebula-keypair"
  floating_ip = "${openstack_compute_floatingip_v2.test.address}"
  security_groups = ["default"]
  provisioner "remote-exec" {
    ...
    connection {
      user = "root"
      key_file = "${var.ssh_key_file}"
    }
  }
}

resource "openstack_compute_instance_v2" "test-the-other" {
  name = "tf-test-2"
  image_id = "62896feb-0c93-49bd-93a3-23f597d3f9ec"
  flavor_id = "n1.small"
  key_pair = "alanturing-nebula-keypair"
  floating_ip = "${openstack_compute_floatingip_v2.test.address}"
  security_groups = ["default"]
  provisioner "remote-exec" {
    ...
    connection {
      user = "root"
      key_file = "${var.ssh_key_file}"
    }
  }
}
```

@jrperritt Any chance you can review and merge this PR. Seems stable enough to me with @hartzell testing.

**Comment by hartzell** [comment]
@jtopjian, **yes**, this work is a **huge** win and I'm quite pleased with it.

@julianenvy, the problem with your scenario is that it doesn't work.  You end up with two instances, one of which has a floating ip and one of which doesn't.  Which one does and which one doesn't is unpredictable.  The only reason that I think that `terraform` might lend a hand here is that Openstack does not protect itself.  Having allocated a floating ip address to one system, there is no requirement that you release it before you allocate it to another.  I don't know if that is true of other components, e.g. can you assign a volume to one system and then assign it again to another w/out an error?

**Pull request closed without merging**
